### ISSUE TITLE
How to use in the declaración de la renta

### ISSUE THREAD

**Issue by rolsoft** [mcgooz/impuestos_cripto#1]
What do I need the capital gains or the income gains for? Where do I input them, I thought I needed to document all transactions. Thanks in advance if you can help. 
_Also congrats on your music, it is quite good_

To be clear, the script works I just don't know what to do with the data.

**Comment by mcgooz** [comment]
Hello. You can use the capital gains results to fill in "Ganancias y pérdidas patrimoniales de transmisión y permuta de monedas virtuales por particulares." For each coin, you'd need to add a new entry with the + sign and then fill in the corresponding amounts: "transmisión", "adquisición", "Clave tipo de contraprestación" etc.

The income gains come from staking and the like, which, according to the info I was given by aeat, goes in casilla 0027.

I'm going to stress that this is a work in progress that is by no means error free. Essentially, it just takes the manual work out of calculating the amounts from the excel provided by Binance. As such, I'd recommend seeking professional advice if you have any doubts over how to correctly fill in the borrador :)
